# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "asgiref"
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "certifi" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "chardet" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "charset-normalizer" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "defusedxml" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "Django" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "django-axes" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "django-crispy-forms" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "django-recaptcha" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "et_xmlfile" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "idna" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "itsdangerous" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "jira" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "mssql-django" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "oauthlib" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "openpyxl" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "packaging" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "pillow" 
    directory: "/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "pyodbc" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "python-decouple" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "python-dotenv" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "pytz" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "reportlab" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "requests" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "requests-oauthlib" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "requests-toolbelt" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "sqlparse" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "typing_extensions" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "tzdata" 
    directory: "/" 
    schedule:
      interval: "daily"

- package-ecosystem: "urllib3" 
    directory: "/" 
    schedule:
      interval: "daily"

